### ISSUE TITLE
Library doesn't work at all. Is it under development?

### ISSUE THREAD

**Issue by swport** [naqel/naqel-php#1]
The flow of the library is difficult to follow. What do you do with the `$naqel` instance that you're creating?

Also, I'm getting this issue:

`Typed property Naqel\Methods\Method::$params must not be accessed before initialization`

Your method class `Naqel\Methods\Method` doesn't have a constructor to init protected params property.

Even after properly setting the client as well as consignee address, I'm still getting:

`Please check the value of Client Address Country Code`

**Comment by mtawil** [comment]
Why are you using method classes? Can you share your code snippet so I can figure out what you are trying to do?

**Comment by swport** [comment]
@mtawil taking directly from your doc:

```php
$naqel->setClientAddress($clientAddress);

$naqel->setClientContact($clientContact);
```

What method would you now call on `$naqel` instance for, let's say, creating a new order or generating a new waybill? What do you do with this created instance? Where do you use it now?

**Comment by mtawil** [comment]
@swport You have to use the whole flow, not part of it:
```php
$naqel = new \Naqel\Naqel([
    'use_sandbox' => true,
    'client_id'   => '[YOUR_CLIENT_ID]',
    'password'    => '[YOUR_CLIENT_PASSWORD]',
    'version'     => '9.0',
]);

// Set your address
$clientAddress = (new \Naqel\Models\ClientAddress())
    ->setPhoneNumber('0555555555')
    ->setFirstAddress('King Abdulaziz Street')
    ->setCountryCode('KSA')
    ->setCityCode('RUH');

// Set your contact
$clientContact = (new \Naqel\Models\ClientContact())
    ->setName('Mohammad')
    ->setPhoneNumber('05xxxxxxxx');

// Attach both address and contact to Naqel instance
$naqel->setClientAddress($clientAddress);
$naqel->setClientContact($clientContact);
```
